# Basic
title = "Raina Doshi"
baseURL = "https://rainadoshi6-portfolio.netlify.app/"
theme = "Vno Hugo"

# Pagination
paginate = 15
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "https://rainadoshi6-portfolio.netlify.app/"
    weight = 10

[taxonomies]
    tag = "introduction"
    
[params]
author = "Raina Doshi"
#subtitle = ""
description = "Masters in Analytics and Management student at London Business School"
welcomeMessage = "Passionate about trekking, cycling and adventures!"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "grey"
#coverImge = ""

[params.comment]
disqus = "vno-hugo"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
#instagram = "https://instagram.com/rainadoshi98"
github = "rainadoshi6"
twitter = "rainadoshi"
#linkedin = "https://www.linkedin.com/in/rainadoshi6/"
#gplus = "107108267983477358170"
mail = "rdoshi.mam2022@london.edu"

[params.ga]
ID = "your_ga_id"
host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[permalinks]
posts = "/:year/:month/:title/"
